### ISSUE TITLE
how to pass CI test when I add new arguments to original function?

### ISSUE THREAD

**Issue by FrozenKP** [sjwhitworth/golearn#173]
https://github.com/FrozenKP/golearn/pull/5

I add Algorithm to KNNClassifier, and Algorithm is either 'kdtree' or 'linear'. Therefore, I add a new argument to knn.NewKnnClassifier() like this:
```go
cls := knn.NewKnnClassifier("euclidean", "linear", 2)
cls := knn.NewKnnClassifier("euclidean", "kdtree", 2)
```
I changed all test and example using knn.NewKNNClassfier(), and it work fine on my computer. But it can't pass CI test may because of CI test refer to old knn.

How can I pass CI test to merge ?

**Comment by FrozenKP** [comment]
hmm...... it pass when I remove ```"linear"``` from ```knn.NewKnnClassifier("euclidean", "linear", 2)```

**Comment by Sentimentron** [comment]
I think it's because you're creating a pull request on your own fork of golearn, whereas the import referenced in `examples/knnclassifier/knnclassifier_iris.go` refers to the `sjwhitworth/golearn/knn` version. It's a bit of a weakness of Go's import system. When you open a pull request against this version of the project, the CI should pass.
